FFMPEG_PREBUILT_LOCAL_PATH := $(call my-dir)
FFMPEG_PREBUILT_OLD_LOCAL_PATH := $(LOCAL_PATH)
LOCAL_PATH := $(FFMPEG_PREBUILT_LOCAL_PATH)
FFMPEG_PREBUILT_LIBS_PATH := ../../../../prebuilt/$(MY_BUILD_DIR)/ffmpeg/lib
FFMPEG_PREBUILT_INCLUDES_PATH := ../../../../prebuilt/$(MY_BUILD_DIR)/ffmpeg/include

include $(CLEAR_VARS)
LOCAL_MODULE := libavcodec_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavcodec_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavdevice_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavdevice_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavfilter_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavfilter_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavformat_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavformat_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavutil_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavutil_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libswresample_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libswresample_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libswscale_neon
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libswscale_neon.so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

LOCAL_PATH := $(FFMPEG_PREBUILT_OLD_LOCAL_PATH)
