FFMPEG_PREBUILT_LOCAL_PATH := $(call my-dir)
FFMPEG_PREBUILT_OLD_LOCAL_PATH := $(LOCAL_PATH)
LOCAL_PATH := $(FFMPEG_PREBUILT_LOCAL_PATH)
FFMPEG_PREBUILT_LIBS_PATH := ../../../prebuilt/$(MY_BUILD_DIR)/ffmpeg/lib
FFMPEG_PREBUILT_INCLUDES_PATH := ../../../prebuilt/$(MY_BUILD_DIR)/ffmpeg/include

MY_LIB_SUFFIX :=
ifneq ($(findstring arm-neon,$(MY_BUILD_DIR)),)
MY_LIB_SUFFIX := _neon
endif

include $(CLEAR_VARS)
LOCAL_MODULE := libavcodec
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavcodec$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavdevice
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavdevice$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavfilter
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavfilter$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavformat
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavformat$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libavutil
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libavutil$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libswresample
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libswresample$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libswscale
LOCAL_SRC_FILES := $(FFMPEG_PREBUILT_LIBS_PATH)/libswscale$(MY_LIB_SUFFIX).so
LOCAL_EXPORT_C_INCLUDES := $(FFMPEG_PREBUILT_INCLUDES_PATH)
include $(PREBUILT_SHARED_LIBRARY)

LOCAL_PATH := $(FFMPEG_PREBUILT_OLD_LOCAL_PATH)
